name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1.5"
    - name: Set up LuaRocks
      uses: leafo/gh-actions-luarocks@v4
    - name: Install dependencies
      run: luarocks install busted
    - name: Install MoonScript
      run: luarocks install moonscript
    - name: Run tests
      run: busted -o utfTerminal
